=== Jrdgogo/Store/Store/src/cn/hncu/container/xmlSchema/XMLSchemaMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.example.org/XMLSchemaMapping" 
        xmlns:tns="http://www.example.org/XMLSchemaMapping" 
        elementFormDefault="qualified">
<element name="configuration">
  <complexType>
     <sequence>
        <element name="typeAliases">
           <complexType>
              <sequence>
                <element name="typeAlias" minOccurs="0" maxOccurs="unbounded">
                   <complexType>
                       <attribute name="class" type="string"></attribute>
                       <attribute name="alias" type="string"></attribute>
                   </complexType>
                </element>
              </sequence>
           </complexType>
        </element>
        <element name="mapping">
           <complexType>
              <sequence>
                <element name="mapper" minOccurs="0" maxOccurs="unbounded">
                   <complexType>
                       <attribute name="url" type="string"></attribute>
                   </complexType>
                </element>
              </sequence>
           </complexType>
        </element>
     </sequence>
  </complexType>
</element>
</schema>

=== Jrdgogo/Store/Store/src/sqlMappingConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns="http://www.example.org/XMLSchemaMapping" 
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:schemaLocation="http://www.example.org/XMLSchemaMapping /WEB-INF/classes/cn/hncu/container/xmlSchema/XMLSchemaMapping.xsd">
	<typeAliases>
		<typeAlias class="cn.hncu.store.domain.User" alias="User"/>
		<typeAlias class="cn.hncu.store.domain.Address" alias="Address"/>
		<typeAlias class="cn.hncu.store.domain.Role" alias="Role"/>
		<typeAlias class="cn.hncu.store.domain.Order" alias="Order"/>
	</typeAliases>
	<mapping>
		<mapper url="cn/hncu/store/domain/xml/User.xml" />
	</mapping>
</configuration>
