=== Jrdgogo/Store/Store/src/cn/hncu/container/xmlSchema/XMLSchemaSql.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.example.org/XMLSchemaSql" 
 xmlns:tns="http://www.example.org/XMLSchemaSql" 
 elementFormDefault="qualified">
 <attributeGroup name="result">
    <attribute name="resultMap" type="IDREF"></attribute>
    <attribute name="resultType" type="string"></attribute>
 </attributeGroup>
 <complexType name="stm" mixed="true">
     <sequence>
       <element name="include" maxOccurs="unbounded" minOccurs="0">
            <complexType>
                 <attribute name="ref" type="IDREF" use="required"></attribute>
            </complexType>
       </element>
     </sequence>
     <attribute name="id" type="ID" use="required"></attribute>
     <attributeGroup ref="tns:result"></attributeGroup>
     <attribute name="sql" type="string"></attribute>
     <attribute name="parameterType" type="string"></attribute>  
 </complexType>
 <simpleType name="javaType">
     <restriction base="token">
        <enumeration value="String"></enumeration>
        <enumeration value="Character"></enumeration>
        <enumeration value="Double"></enumeration>
        <enumeration value="Float"></enumeration>
        <enumeration value="Long"></enumeration>
        <enumeration value="Integer"></enumeration>
        <enumeration value="Short"></enumeration>
        <enumeration value="Byte"></enumeration>
        <enumeration value="Boolean"></enumeration>
        <enumeration value="char"></enumeration>
        <enumeration value="double"></enumeration>
        <enumeration value="float"></enumeration>
        <enumeration value="long"></enumeration>
        <enumeration value="int"></enumeration>
        <enumeration value="short"></enumeration>
        <enumeration value="byte"></enumeration>
        <enumeration value="boolean"></enumeration>
     </restriction>
 </simpleType>
 <simpleType name="jdbcType">
     <restriction base="token">
        <enumeration value="BIGINT"></enumeration>
        <enumeration value="BINARY"></enumeration>
        <enumeration value="BIT"></enumeration>
        <enumeration value="BLOB"></enumeration>
        <enumeration value="BOOL"></enumeration>
        <enumeration value="BOOLEAN"></enumeration>
        <enumeration value="CHAR"></enumeration>
        <enumeration value="DATE"></enumeration>
        <enumeration value="DATETIME"></enumeration>
        <enumeration value="DECIMAL"></enumeration>
        <enumeration value="DOUBLE"></enumeration>
        <enumeration value="ENUM"></enumeration>
        <enumeration value="FLOAT"></enumeration>
        <enumeration value="INT"></enumeration>
        <enumeration value="LONGBLOB"></enumeration>
        <enumeration value="LONGTEXT"></enumeration>
        <enumeration value="MEDIUMBLOB"></enumeration>
        <enumeration value="MEDIUMINT"></enumeration>
        <enumeration value="MEDIUMTEXT"></enumeration>
        <enumeration value="NUMERIC"></enumeration>
        <enumeration value="REAL"></enumeration>
        <enumeration value="SET"></enumeration>
        <enumeration value="SMALLINT"></enumeration>
        <enumeration value="TEXT"></enumeration>
        <enumeration value="TIME"></enumeration>
        <enumeration value="TIMESTAMP"></enumeration>
        <enumeration value="TINYBLOB"></enumeration>
        <enumeration value="TINYINT"></enumeration>
        <enumeration value="TINYTEXT"></enumeration>
        <enumeration value="VARBINARY"></enumeration>
        <enumeration value="VARCHAR"></enumeration>
        <enumeration value="YEAR"></enumeration>
     </restriction>
 </simpleType>
 <complexType name="attribute">
     <attribute name="property" type="string"></attribute>
     <attribute name="column" type="string"></attribute>
     <attribute name="javaType" type="tns:javaType"></attribute>
     <attribute name="jdbcType" type="tns:jdbcType"></attribute>
 </complexType>
 <complexType name="resultType">
      <sequence>
           <element name="id" minOccurs="0" maxOccurs="1" type="tns:attribute"></element>
           <element name="result" minOccurs="0" maxOccurs="unbounded" type="tns:attribute"></element>
           <element name="association" minOccurs="0" maxOccurs="unbounded" type="tns:resultType"></element>
           <element name="collection" minOccurs="0" maxOccurs="unbounded" type="tns:resultType"></element>
      </sequence>
      <attribute name="property" type="string"></attribute>
      <attribute name="javaType" type="string"></attribute>
 </complexType>
 <complexType name="mapping">
       <sequence>
           <element name="resultMap" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                   <sequence>
                      <element name="id" minOccurs="0" maxOccurs="1" type="tns:attribute"></element>
                      <element name="result" minOccurs="0" maxOccurs="unbounded" type="tns:attribute"></element>
                      <element name="association" minOccurs="0" maxOccurs="unbounded" type="tns:resultType"></element>
                      <element name="collection" minOccurs="0" maxOccurs="unbounded" type="tns:resultType"></element>
                   </sequence>
                   <attribute name="id" type="ID"></attribute>
                   <attribute name="type" type="string" use="required"></attribute>
                </complexType>
           </element>
           <element name="sql" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                   <simpleContent>
                        <extension base="string">
                            <attribute name="id" type="ID" use="required"></attribute>
                        </extension>
                   </simpleContent>
                </complexType>
           </element>
           <element name="select" minOccurs="0" maxOccurs="unbounded" type="tns:stm"></element>
           <element name="insert" minOccurs="0" maxOccurs="unbounded" type="tns:stm"></element>
           <element name="update" minOccurs="0" maxOccurs="unbounded" type="tns:stm"></element>
           <element name="delete" minOccurs="0" maxOccurs="unbounded" type="tns:stm"></element>
       </sequence>
       <attribute name="class" type="string" use="required"></attribute>
 </complexType>
 <element name="mapping">
    <complexType>
       <sequence>
            <element name="mapper" minOccurs="0" maxOccurs="unbounded" type="tns:mapping">
            </element>
       </sequence>
    </complexType>
 </element>
</schema>

=== Jrdgogo/Store/Store/src/cn/hncu/store/domain/xml/User.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns="http://www.example.org/XMLSchemaSql" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://www.example.org/XMLSchemaSql /WEB-INF/classes/cn/hncu/container/xmlSchema/XMLSchemaSql.xsd">
  <mapper class="cn.hncu.store.domain.mapping.UserMapping">
    <resultMap type="User" id="detailUser">
       <id property="id" column="uid" javaType="String" jdbcType="VARCHAR"/>
       <result property="name" column="uname" javaType="String" jdbcType="VARCHAR"/>
       <result property="realName" column="urealName" javaType="String" jdbcType="VARCHAR"/>
       <result property="phone" column="uphone" javaType="String" jdbcType="VARCHAR"/>
       <result property="email" column="uemail" javaType="String" jdbcType="VARCHAR"/>
       <result property="sex" column="usex" javaType="String" jdbcType="ENUM"/>
       <result property="birth" column="ubirth" javaType="String" jdbcType="VARCHAR"/>
       <result property="address" column="uaddress" javaType="String" jdbcType="VARCHAR"/>
       <result property="createTime" column="ucreateTime" javaType="String" jdbcType="VARCHAR"/>
       <result property="lastLoginIP" column="ulastLoginIP" javaType="String" jdbcType="VARCHAR"/>
       <result property="lastLoginTime" column="ulastLoginTime" javaType="String" jdbcType="VARCHAR"/>
       <result property="descr" column="udescr" javaType="String" jdbcType="VARCHAR"/>
       <collection property="photo" javaType="byte">
	       <id column="uphoto" jdbcType="BLOB"/>
       </collection>
       <collection property="addresses" javaType="Address">
	       <id property="id" column="aid" javaType="String" jdbcType="VARCHAR"/>
	       <result property="zipCode" column="azipCode" javaType="String" jdbcType="VARCHAR"/>
	       <result property="address" column="aaddress" javaType="String" jdbcType="VARCHAR"/>
       </collection>
       <collection property="roles" javaType="Role">
	       <id property="id" column="rid" javaType="String" jdbcType="VARCHAR"/>
	       <result property="parentId" column="rparentId" javaType="String" jdbcType="VARCHAR"/>
	       <result property="name" column="rname" javaType="String" jdbcType="VARCHAR"/>
	       <result property="createTime" column="rcreateTime" javaType="String" jdbcType="VARCHAR"/>
	       <result property="descr" column="rdescr" javaType="String" jdbcType="VARCHAR"/>
       </collection>
       <collection property="orders" javaType="Order">
	       <id property="id" column="oid" javaType="String" jdbcType="VARCHAR"/>
	       <result property="consignee" column="oconsignee" javaType="String" jdbcType="VARCHAR"/>
	       <result property="paytype" column="opaytype" javaType="char" jdbcType="CHAR"/>
	       <result property="amount" column="oamount" javaType="double" jdbcType="NUMERIC"/>
	       <result property="state" column="ostate" javaType="char" jdbcType="CHAR"/>
	       <result property="orderdate" column="oorderdate" javaType="String" jdbcType="VARCHAR"/>
       </collection>
    </resultMap>
    <sql id="userfield">user.id AS uid,user.name AS uname,user.realName AS urealName,user.phone AS uphone,user.email AS uemail,
                        user.sex AS usex,user.birth AS ubirth,user.address AS uaddress,user.photo AS uphoto,user.createTime AS ucreateTime,
                        user.lastLoginIP AS ulastLoginIP,user.lastLoginTime AS ulastLoginTime,user.descr AS udescr</sql> 
    <sql id="addressfield">address.id AS aid,address.zipCode AS azipCode,address.address AS aaddress</sql>                    
    <sql id="rolefield">role.id AS rid,role.parentId AS rparentId,role.name AS rname,role.createTime AS rcreateTime,role.descr AS rdescr</sql>                    
    <sql id="orderfield">ord.id AS oid,ord.consignee AS oconsignee,ord.paytype AS opaytype,ord.amount AS oamount,ord.state AS ostate,ord.orderdate AS oorderdate</sql>                    
    <select id="getAllUser" resultMap="detailUser">
        SELECT <include ref="userfield"></include>,
               <include ref="rolefield"></include>,
               <include ref="orderfield"></include>,
               <include ref="addressfield"></include>
               FROM users user LEFT JOIN userole ur ON user.id=ur.user
                               LEFT JOIN roles role ON ur.role=role.id
                               LEFT JOIN orders ord ON user.id=ord.user
                               LEFT JOIN addresses address ON user.id=address.user
    </select>
    <select id="getSingleUser" sql="sql" resultType="User">
        SELECT * FROM users ${sql}
    </select>
    <insert id="register" sql="sql" resultType="boolean">
        INSERT INTO users(id,name,password,phone,email) ${sql}
    </insert>
    <update id="update" sql="sql" resultType="boolean">
        DELETE FROM users ${sql}
    </update>
    <delete id="del" sql="sql" resultType="boolean">
        UPDATE users ${sql}
    </delete>
  </mapper>
</mapping>
